import './globals.css'
import { LayoutRootProps } from '@/interface'
import type { Metadata } from 'next'


export const metadata: Metadata = {
  title: 'NextJS 13.4 Start Kit for Grafbase with NextAuth ',
  description: 'Generated by create next app',
};

export default function RootLayout(props:LayoutRootProps) {
  return (
    <html lang="en">
      <body>{props.children}</body>
    </html>
  )
}
