import '@/styles/globals.scss';
import { LayoutRootProps } from '@/interface';
import type { Metadata } from 'next';
import { NextAuthProvider } from '@/lib/providers/next-auth';
import Navbar from '@/components/main/navbar';

export const metadata: Metadata = {
  title: 'Outerbase',
  description: 'Generated by create next app',
};

export default function RootLayout(props: LayoutRootProps) {
  return (
    <html lang='en'>
      <NextAuthProvider>
        <body>
          <Navbar />
          <main>{props.children}</main>
        </body>
      </NextAuthProvider>
    </html>
  );
}
