import '@/styles/global.css';
import Navbar from '@/components/dashboard/navbar';
import Sidebar from '@/components/sidebar';
import { ApolloProviderWrapper } from '@/lib/providers/apollo-graphql';
import { NextAuthProvider } from '@/lib/providers/next-auth';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <ApolloProviderWrapper>
        <NextAuthProvider>
          <body className='w-full h-screen overflow-y-hidden bg-gray-50'>
            <Navbar />
            <section className='w-full flex'>
              <Sidebar />
              <main className='w-full h-[90vh] overflow flex-1 p-4'>
                {children}
              </main>
            </section>
          </body>
        </NextAuthProvider>
      </ApolloProviderWrapper>
    </html>
  );
}
