import '@/styles/global.css';
import Navbar from '@/components/navbar';
import { LayoutRootProps } from '@/interface';
import { ApolloProviderWrapper } from '@/lib/providers/apollo-graphql';
import { NextAuthProvider } from '@/lib/providers/next-auth';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

export default function RootLayout(props: LayoutRootProps) {
  return (
    <html lang='en'>
      <ApolloProviderWrapper>
        <NextAuthProvider>
          <Navbar />
          <main>{props.children}</main>
        </NextAuthProvider>
      </ApolloProviderWrapper>
    </html>
  );
}
