import Navbar from '@/components/navbar';
import '@/styles/global.css';
import { LayoutRootProps } from '@/interface';
import type { Metadata } from 'next';
import { ApolloProviderWrapper } from '@/lib/providers/apollo-graphql';
import { NextAuthProvider } from '@/lib/providers/next-auth';

export const metadata: Metadata = {
  title: 'Bloggkie | Blog Posts',
  description: 'Generated by create next app',
};

export default function RootLayout(props: LayoutRootProps) {
  return (
    <html lang='en'>
      <ApolloProviderWrapper>
        <NextAuthProvider>
          <body>
            <Navbar />
            <main>{props.children}</main>
          </body>
        </NextAuthProvider>
      </ApolloProviderWrapper>
    </html>
  );
}
